#!/usr/bin/env sh

setbg &		# Set the background
xrdb -merge ~/.config/x11/Xresources &
redshift -l 52.7:21.6 -t 6500:3300 -g 0.8 -m randr &
pywalinit &	# sets color scheme
# Switch to US international with Caps as Mod/Escape
setxkbmap -option caps:swapescape && killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape' &
sxhkd &	# Bind keys
# Properties button extra Mod/Escape
xmodmap -e 'keycode 135 = Super_R' &
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
compton --config ~/.config/compton/compton.conf &
# xcompmgr -CcfF -D2 &
mpdupdate &
sudo rfkill unblock bluetooth &
myanacron &
