mp.add_key_binding("MOUSE_BTN0", function()
    local x, y = mp.get_mouse_pos()
    local time_pos = mp.get_property_number("time-pos")
    mp.osd_message("x: " ..x.. " y: " ..y.. "\n" ..time_pos.. "", 1)
end)
